INSERT INTO tb_category(name) VALUES ('Medicamentos');
INSERT INTO tb_category(name) VALUES ('Cosméticos');
INSERT INTO tb_category(name) VALUES ('Higiene');

INSERT INTO tb_product (name, price, description, img_url) VALUES ('Dorflex', 20.31, 'Dorflex é um analgésico e relaxante muscular que alivia dores associadas a contraturas musculares e cefaleias tensionais. Dorflex atua rapidamente no alívio da dor e no relaxamento dos músculos.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/dorflex.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Allegra 120mg', 76.38, 'O Allegra 120mg é um anti-histamínico que contém cloridrato de fexofenadina, indicado para o alívio dos sintomas da rinite alérgica e urticária. É eficaz no tratamento de sintomas como coriza, espirros, coceira nos olhos, nariz e garganta.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/allegra.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Dipirona 1g', 20.57, 'A Dipirona Sódica 500mg é um medicamento analgésico e antitérmico, pertencente ao grupo das pirazolonas.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/dipirona.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Levotiroxina Sódica 200mg', 36.73, 'A Levotiroxina 200 mcg  é um medicamento usado para o tratamento do hipertireoidismo, uma condição onde a glândula tireoide produz muito hormônio.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/levo.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Vonau Flash 4mg', 83.49, 'O Vonau Flash 4 mg é um medicamento utilizado para o tratamento e prevenção de náuseas e vômitos.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/vonau.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Naproxeno Sódico 550mg', 46.79, 'Este medicamento é indicado para dores agudas causadas por inflamação como por exemplo, dor de garganta, febre em adultos, dor de dente, dor abdominal e pélvica, dor de cabeça, sintomas de gripe e resfriado.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/naproxeno.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Tramadol 50mg', 31.45, 'O cloridrato de tramadol é indicado para analgesia (alívio da dor) de intensidade moderada a grave; independente do tempo que esta dor atinge o paciente, seja a dor do tipo aguda, subaguda e crônica.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/tramadol.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Protetor Solar Facial FPS60', 99.90, 'O Protetor Solar Facial Episol Antiox FPS60 é um fotoprotetor de alta proteção que combate os efeitos nocivos dos raios solares UVA e UVB.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/protetor.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Hidratante Facial', 59.49, 'O Hidratante Facial Neutrogena Hydro Boost Water Gel 50g, é o dermocosmético ideal para os cuidados com o rosto com uma fórmula ultraleve que repõe os níveis de água da pele e hidrata por até 48 horas.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/hidratante.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Sabonete Líquido 300ml', 89.99, 'Fórmula que limpa profundamente a pele e reduz a aparência dos poros. Clinicamente testado para remover sujeira, excesso de oleosidade e maquiagem sem deixar a pele seca ou repuxada.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/saboneteli.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Óleo de banho 400ml', 129.90, 'O Óleo de Banho Protetor ISDIN Ureadin Calm é um óleo de banho da marca ISDIN. Este produto é especialmente formulado para proporcionar limpeza e hidratação corporal para todos os tipos de pele.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/oleo.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Desodorante 50ml', 9.39, 'O Desodorante Rexona Antibacterial Invisible Women Rollon foi desenvolvido para oferecer proteção eficaz contra o suor e os odores, com a vantagem de uma fórmula que não mancha as roupas, sejam elas claras ou escuras.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/desodorante.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Creme Dental 140g', 19.99, 'Conheça o Creme Dental Sensodyne Rápido Alívio, sua nova arma contra a sensibilidade dentária. Com Acetato de Estrôncio em sua fórmula, ele oferece proteção e alívio duradouros, garantindo um sorriso sem dor com escovação diária.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/cremedental.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Benegrip', 38.79, 'Benegrip é um medicamento antigripal que possui a combinação de três ativos importantes: Dipirona monoidratada (500mg): combate a dor e a febre;Maleato de clorfeniramina (2mg): ação antialérgica; Cafeína (30mg): ação estimulante.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/benegripe.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Vitamina C', 103.90, 'Targifo + C é um medicamento que combate o cansaço físico e mental, à base de arginina e vitamina C. Também fortalece a imunidade e tem ação antioxidante, prevenindo o envelhecimento precoce do organismo.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/vitaminac.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Vitamina D 1000UI ', 55.90, 'O Addera D3 1000UI é um medicamento à base de Vitamina D, indicado para o tratamento auxiliar de condições relacionadas à desmineralização óssea, como osteoporose, osteomalácia, raquitismo.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/vitaminad.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Buscopan Composto', 19.89, 'O Buscopan Composto é uma combinação de butilbrometo de escopolamina e dipirona, proporcionando alívio rápido e prolongado de cólicas, dores e desconforto abdominal.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/buscopam.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Escova de Dente Elétrica', 227.49, 'Escova De Dente Elétrica Philips Colgate Sonicpro Kids 1 Unid', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/escovaeletrica.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Creme Dental Para Sensibilidade 90g', 15.99, 'Descubra o Creme Dental Colgate Sensitive Pro Alívio Imediato Original 90g, a solução definitiva para um sorriso sem sensibilidade. Com sua fórmula inovadora, oferece uma proteção robusta, garantindo um alívio rápido e eficaz da sensibilidade dentária.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/colgate.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Probiótico 5ml', 40.99, 'A Enterogermina é um probiótico que contribui para o equilíbrio da flora intestinal, cada flaconete com 5ml é composto por água e cerca de 2 bilhões de esporos de Bacillus clausii.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/probiotico.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Cetoconazol Shampoo 100ml', 42.99, 'Cetoconazol Shampoo é indicado para o tratamento da dermatite seborreica (caspa) em adultos, aliviando sintomas como coceira e descamação do couro cabeludo. Produto de uso externo (tópico), com fragrância suave de ervas.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/cetoconazol.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Acetilcisteina 40mg Xarope 120ml', 28.29, 'A Acetilcisteína 40mg Xarope é um medicamento expectorante utilizado para facilitar a eliminação de secreções respiratórias espessas e viscosas, tornando-as mais fluidas. Ele é indicado para o tratamento de gripes.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/xarope.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('LuftaGastro Líquido 10 ml', 40.82, 'O LuftaGastro Líquido é um medicamento indicado para aliviar sintomas de refluxo gástrico, como azia e queimação, causados pela má digestão.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/lufta.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Solução Fisiológica 0.9% 500ml', 9.99, 'Dauf é nossa marca presente nas mais diversas categorias, oferecendo conveniência com qualidade para os nossos consumidores. A Solução Fisiológica Pro Sono Dauf é um produto versátil, auxilia em diversos tipos de procedimentos.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/soro.png');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Sal de Fruta Eno 5g', 4.19, 'O Sal de Fruta Eno é um antiácido indicado para o alívio da azia, má digestão e outros transtornos estomacais, como excesso de acidez e indigestão ácida. Em formato de pó efervescente.', 'https://github.com/Jullianag/farmacia/tree/main/src/main/resources/images/sal.png');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 1);

INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Maria Brown', 'maria@gmail.com', '988888888', '$2a$10$FRtbNAa5nTXbPD99AJGIY.299H8MJzyuxNC0XwuIvZay5iBcsHs92', '2001-07-25');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Alex Green', 'alex@gmail.com', '977777777', '$2a$10$FRtbNAa5nTXbPD99AJGIY.299H8MJzyuxNC0XwuIvZay5iBcsHs92', '1987-12-13');

INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-07-25T13:00:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-07-29T15:50:00Z', 3, 2);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-08-03T14:20:00Z', 0, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-06-03T14:16:00Z', 1, 2);

INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 1, 2, 20.31);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 3, 1, 20.57);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (2, 3, 1, 20.57);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (3, 1, 1, 20.31);

INSERT INTO tb_payment (order_id, moment) VALUES (1, TIMESTAMP WITH TIME ZONE '2024-07-25T15:00:00Z');
INSERT INTO tb_payment (order_id, moment) VALUES (2, TIMESTAMP WITH TIME ZONE '2024-07-30T11:00:00Z');
INSERT INTO tb_payment (order_id, moment) VALUES (3, TIMESTAMP WITH TIME ZONE '2024-05-18T11:00:00Z');
